<%@ page contentType="text/html;charset=UTF-8" language="java" pageEncoding="UTF-8"%>
<div>
    <table style="color: white;" border="1px">
        <tr>
            <td rowspan="3">酒厂</td>
            <td>Admin</td>
            <td>jc01</td>
        </tr>
        <tr>
            <td>酒厂管理人员</td>
            <td>jc11</td>
        </tr>
        <tr>
            <td>酒厂业务员</td>
            <td>jc21</td>
        </tr>
        <tr>
            <td rowspan="5">运营管理方</td>
            <td>Admin</td>
            <td>yy01</td>
        </tr>
        <tr>
            <td>中酒管理人员</td>
            <td>yy11</td>
        </tr>
        <tr>
            <td>中酒事务助理</td>
            <td>yy21</td>
        </tr>
        <tr>
            <td>中酒省区经理</td>
            <td>yy31</td>
        </tr>
        <tr>
            <td>中酒渠道总监</td>
            <td>yy41</td>
        </tr>
        <tr>
            <td rowspan="4">金融服务方</td>
            <td>Admin</td>
            <td>jr11</td>
        </tr>
        <tr>
            <td>真安管理人员</td>
            <td>jr21</td>
        </tr>
        <tr>
            <td>真安信审员</td>
            <td>jr31</td>
        </tr>
        <tr>
            <td>真安风控中心</td>
            <td>jr41</td>
        </tr>
        <tr>
            <td rowspan="3">监管方</td>
            <td>Admin</td>
            <td>jg01</td>
        </tr>
        <tr>
            <td>监管方管理人员</td>
            <td>jg11</td>
        </tr>
        <tr>
            <td>监管方操作员</td>
            <td>jg21</td>
        </tr>
        <tr>
            <td rowspan="3">资方</td>
            <td>Admin</td>
            <td>zf01</td>
        </tr>
        <tr>
            <td>资方管理人员</td>
            <td>zf11</td>
        </tr>
        <tr>
            <td>资方操作员</td>
            <td>zf21</td>
        </tr>
        <tr>
            <td rowspan="3">保险履约方</td>
            <td>Admin</td>
            <td>bx01</td>
        </tr>
        <tr>
            <td>履约保险方管理人员</td>
            <td>bx11</td>
        </tr>
        <tr>
            <td>履约保险方操作员</td>
            <td>bx21</td>
        </tr>
    </table>
</div>
